spring:
  application:
    name: free-board
    
---

server:
  port: 8080

---

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
---

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.example.board.common.mybatis
